name: Build and upload linux-x64

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
    build-linux-x64:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Go
              uses: actions/setup-go@v4
              with:
                go-version: '1.21'

            - name: Cache Go modules
              uses: actions/cache@v4
              with:
                path: |
                  ~/.cache/go-build
                  ~/go/pkg/mod
                key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
                restore-keys: |
                  ${{ runner.os }}-go-

            - name: Build (linux-x64)
              run: |
                mkdir -p dist
                GOOS=linux GOARCH=amd64 go build -o dist/wireguard-go-linux-x64 ./...

            - name: Upload artifact (linux-x64)
              uses: actions/upload-artifact@v4
              with:
                name: wireguard-go-linux-x64
                path: dist/wireguard-go-linux-x64